FROM python:3.11-slim

WORKDIR /app

COPY requirements_train.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    -r requirements_train.txt

COPY . .

CMD ["python", "training/train_sentiment.py"]