name: Deploy API to Azure

on:
  push:
    branches:
      - model_only
    paths:
      - "main.py"
      - "inference/**"
      - "scripts/**"
      - "Dockerfile"
      - "requirements_api.txt"

env:
  ACR_NAME: ${{ vars.ACR_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  IMAGE_NAME: ${{ vars.API_IMAGE_NAME }}
  CONTAINER_NAME: ${{ vars.API_CONTAINER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Docker image
        run: |
          VERSION=$(date +%Y%m%d_%H%M)

          docker build -f Dockerfile -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION

          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: Update Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ env.IMAGE_TAG }}